project:
  type: website
  output-dir: docs
execute: 
  freeze: auto
  cache: true

website:
  title: "NRP - Supplement"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_datapreparation.qmd
      - 02_networkestimation.qmd
      - sessioninformation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin
    code-fold: true

knitr:
  opts_chunk:
    code_fold: true

editor: visual

