project:
  type: website
  output-dir: docs
execute: 
  freeze: auto

website:
  title: "NRP - Supplement"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_datapreparation.qmd
      - sessioninformation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin

editor: visual

