---
title: "Networks of Risk Perception - Supplementary Website"
---

This website is a supplement to the chapter"Networks of Risk Perception" by Jan-Erik Anderson, Alisa Puustinen & Oliver Saal, to be published in the anthology *Information Resilience in a Complex System of National Security*.

The website contains the necessary R code to reproduce all analyses published in the original article. It also contains robustness checks and other model analyses deemed important for the reproduction and confirmation of the results, but not published in the main manuscript.

Note that most data preparation is ran in this document in a pre-rendering script called `prerender.R`. The code is added at appropriate places in the text for visualisation, with the Quarto option of `eval: false`. The complete pre-rendering script is found in the [GitHub source of this page](https://github.com/osaal/NRP_supplementary/blob/master/prerender.R).

[For questions regarding the article itself]{.underline}, please contact the corresponding author according to the anthology instructions.

[For questions regarding this supplementary website]{.underline}, please contact O. Saal. Contact information is published in the anthology chapter.

This website was written using the **Quarto** publishing system and hosted with **GitHub Pages.**
